// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_proyect.Models;

#nullable disable

namespace backend_proyect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119074219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend_proyect.Models.Entities.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_almacen");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("InformacionContacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<bool>("PerteneceCs")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pertenece_es");

                    b.Property<int>("UsuarioMovimientoIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("UsuarioMovimientoIdUsuario");

                    b.ToTable("almacenes", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<string>("InformacionContacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioMovimientoIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdCliente");

                    b.HasIndex("UsuarioMovimientoIdUsuario");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.ConceptoEntradaSalida", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_concepto");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdConcepto");

                    b.ToTable("conceptos_entrada_salida", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ciudad");

                    b.Property<int?>("CodigoPostal")
                        .HasColumnType("int")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("colonia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("municipio");

                    b.Property<int?>("NoExterior")
                        .HasColumnType("int")
                        .HasColumnName("no_exterior");

                    b.Property<int?>("NoInterior")
                        .HasColumnType("int")
                        .HasColumnName("no_interior");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rfc");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefono");

                    b.Property<int>("UsuarioMovimientoIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("UsuarioMovimientoIdUsuario");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.EstadoProducto", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdEstado");

                    b.ToTable("estado_productos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.ExcepcionProducto", b =>
                {
                    b.Property<int>("IdExcepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_excepcion");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdExcepcion");

                    b.ToTable("excepciones_productos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Familia", b =>
                {
                    b.Property<int>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_familia");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdFamilia");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.MotivoTraspaso", b =>
                {
                    b.Property<int>("IdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_motivo");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdMotivo");

                    b.ToTable("motivos_traspasos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Pasillo", b =>
                {
                    b.Property<int>("IdPasillo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pasillo");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdPasillo");

                    b.ToTable("pasillos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdPerfil");

                    b.ToTable("perfiles", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Presentacion", b =>
                {
                    b.Property<int>("IdPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_presentacion");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdPresentacion");

                    b.ToTable("presentacion", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<byte[]>("Fotografia")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("fotografia");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdExcepcion")
                        .HasColumnType("int")
                        .HasColumnName("id_excepcion");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("int")
                        .HasColumnName("id_familia");

                    b.Property<int>("IdPresentacion")
                        .HasColumnType("int")
                        .HasColumnName("id_presentacion");

                    b.Property<int>("IdSubtipo")
                        .HasColumnType("int")
                        .HasColumnName("id_subtipo");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdExcepcion");

                    b.HasIndex("IdFamilia");

                    b.HasIndex("IdPresentacion");

                    b.HasIndex("IdSubtipo");

                    b.HasIndex("IdTipo");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<string>("InformacionContacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<int>("UsuarioMovimientoIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdProveedor");

                    b.HasIndex("UsuarioMovimientoIdUsuario");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Rack", b =>
                {
                    b.Property<int>("IdRack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rack");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("Columna")
                        .HasColumnType("int")
                        .HasColumnName("columns");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("IdPasillo")
                        .HasColumnType("int")
                        .HasColumnName("id_pasillo");

                    b.Property<int>("Nivel")
                        .HasColumnType("int")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<int>("Subnivel")
                        .HasColumnType("int")
                        .HasColumnName("subnivel");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdRack");

                    b.HasIndex("IdPasillo");

                    b.ToTable("racks", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.SubtipoProducto", b =>
                {
                    b.Property<int>("IdSubtipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_subtipo");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdSubtipo");

                    b.ToTable("subtipos_productos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.TipoProducto", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdTipo");

                    b.ToTable("tipos_productos", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaUltMov")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ult_mov");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("UsuarioUltMov")
                        .HasColumnType("int")
                        .HasColumnName("usuario_ult_mov");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPerfil");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Almacen", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.Empresa", "Empresa")
                        .WithMany("Almacenes")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyect.Models.Entities.Usuario", "UsuarioMovimiento")
                        .WithMany()
                        .HasForeignKey("UsuarioMovimientoIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("UsuarioMovimiento");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Cliente", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.Usuario", "UsuarioMovimiento")
                        .WithMany()
                        .HasForeignKey("UsuarioMovimientoIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMovimiento");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Empresa", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.Usuario", "UsuarioMovimiento")
                        .WithMany()
                        .HasForeignKey("UsuarioMovimientoIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMovimiento");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Producto", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.EstadoProducto", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyect.Models.Entities.ExcepcionProducto", "Excepcion")
                        .WithMany()
                        .HasForeignKey("IdExcepcion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyect.Models.Entities.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyect.Models.Entities.Presentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("IdPresentacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyect.Models.Entities.SubtipoProducto", "Subtipo")
                        .WithMany()
                        .HasForeignKey("IdSubtipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_proyect.Models.Entities.TipoProducto", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Excepcion");

                    b.Navigation("Familia");

                    b.Navigation("Presentacion");

                    b.Navigation("Subtipo");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Proveedor", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.Usuario", "UsuarioMovimiento")
                        .WithMany()
                        .HasForeignKey("UsuarioMovimientoIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMovimiento");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Rack", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.Pasillo", "Pasillo")
                        .WithMany()
                        .HasForeignKey("IdPasillo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pasillo");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Usuario", b =>
                {
                    b.HasOne("backend_proyect.Models.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Empresa", b =>
                {
                    b.Navigation("Almacenes");
                });

            modelBuilder.Entity("backend_proyect.Models.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
